version: '3.8'

services:
  haproxy:
    image: haproxy:lts-bookworm
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/etc/haproxy/certs
    restart: unless-stopped
