version: '3.8'

services:
  haproxy:
    image: haproxy:lts-bookworm
    container_name: haproxy
    network_mode: host
    volumes:
      - /home/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - /home/certs:/etc/haproxy/certs
    restart: always

  redis:
    image: redis:latest
    restart: always
    network_mode: host
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - /home/redis:/data
